### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by ghost** [ROBOTIS-GIT/turtlebot3_home_service_challenge#11]
https://github.com/ROBOTIS-GIT/turtlebot3_home_service_challenge/blob/49e25c01c1eade4c27cd93d8c7862c4e10ba8a62/turtlebot3_home_service_challenge_manager/src/tb3_hsc_manager_core.cpp#L291
This line:
// laod scenario

Should be this:
// load scenario

**Comment by ROBOTIS-Will** [comment]
Thank you for reporting the typo.
It is fixed and will be merged soon.
https://github.com/ROBOTIS-GIT/turtlebot3_home_service_challenge/commit/16d6dc5d92f433224d1bab5fae56c9837b1957ed
Thank you.
