### ISSUE TITLE
[ERROR] [1599700743.912509523]: Failed to fetch current robot state

### ISSUE THREAD

**Issue by ChristianDeng** [ROBOTIS-GIT/turtlebot3_home_service_challenge#12]
![can_not_get_pose](https://user-images.githubusercontent.com/24356107/92675740-b2272880-f352-11ea-95df-5366e9ade4c9.png)

I met a error when RESET Turtlebot!!
It came out :
[ INFO] [1599700743.912292177]: Didn't received robot state (joint angles) with recent timestamp within 1 seconds.
Check clock synchronization if your are running ROS across multiple machines!
[ERROR] [1599700743.912509523]: Failed to fetch current robot state
[tb3_hsc/tb3_hsc_manager_node-1] process has died [pid 21029, exit code -11, cmd /home/jtdq/catkin_ws/devel/lib/turtlebot3_home_service_challenge_manager/tb3_hsc_manager_node __name:=tb3_hsc_manager_node __log:=/home/jtdq/.ros/log/7446ed38-f303-11ea-a30c-1008b1d49441/tb3_hsc-tb3_hsc_manager_node-1.log].
log file: /home/jtdq/.ros/log/7446ed38-f303-11ea-a30c-1008b1d49441/tb3_hsc-tb3_hsc_manager_node-1*.log
after that, the manger reported errors:
[ERROR] [1599700927.852128908]: Ignoring transform for child_frame_id "ar_marker_0" from authority "unknown_publisher" because of a nan value in the transform (-nan -nan -nan) (-nan -nan -nan -nan)
[ERROR] [1599700927.978164142]: Ignoring transform for child_frame_id "ar_marker_0" from authority "unknown_publisher" because of an invalid quaternion in the transform (-nan -nan -nan -nan)
[ERROR] [1599700927.978255172]: Ignoring transform for child_frame_id "ar_marker_0" from authority "unknown_publisher" because of a nan value in the transform (-nan -nan -nan) (-nan -nan -nan -nan)

how can I solve those problems, thanks

**Comment by ChristianDeng** [comment]
and add another screenshot
![problem2](https://user-images.githubusercontent.com/24356107/92676598-7f7e2f80-f354-11ea-90e5-6c664449d42b.png)

**Comment by ROBOTIS-Will** [comment]
@ChristianDeng Sorry for the delay. Have you tried the time sync between the TurtleBot3 Raspberry Pi and your Remote PC?
In case your WiFi network is unstable, please also try with the ethernet cable.
https://emanual.robotis.com/docs/en/platform/turtlebot3/faq/#timesync-between-turtlebot3-and-remote-pc

**Comment by ChristianDeng** [comment]
> @ChristianDeng Sorry for the delay. Have you tried the time sync between the TurtleBot3 Raspberry Pi and your Remote PC?
> In case your WiFi network is unstable, please also try with the ethernet cable.
> https://emanual.robotis.com/docs/en/platform/turtlebot3/faq/#timesync-between-turtlebot3-and-remote-pc

Yes, I have tried, it did not work.

**Comment by ROBOTIS-Will** [comment]
Have you also tried with ethernet cables instead of wifi?

**Comment by ChristianDeng** [comment]
> Have you also tried with ethernet cables instead of wifi?

It was solved by changing using TX2 to run the code, It's because my computer doesn't have enough memory and computation, thanks.
