### ISSUE TITLE
Question - Custom object & target locations

### ISSUE THREAD

**Issue by ghost** [ROBOTIS-GIT/turtlebot3_home_service_challenge#5]
Hi!

I have a question about the room.yaml file. For my own project, I will be moving one object from location A to location B. The coordinates for these two locations are obviously unique to my situation and thus they are not the same as the coordinates that are currently in the room.yaml file.

Therefore, I would like to change the coordinates of both the object and the target, but I don't know how the coordinates are defined. Is it measured in meters? And from what point? And what do the position coordinates of the AR tags refer to?

Here's what I mean with my question, with the actual code as a reference:

> room_1 :
  name : toilet
  object :
    marker : ar_marker_0
    position : [0.25, 0, 0.15] --> what do these numbers mean and how are they determined?
  target :
    marker : ar_marker_4
    position : [0.25, 0, 0.15] --> what do these numbers mean and how are they determined?
  x : [1.5, 0.6] --> where do these numbers refer to, what do they mean and how are they determined?
  y : [1.5, 0.2] --> where do these numbers refer to, what do they mean and how are they determined?

I hope someone can help me answer this, as I'm currently stuck with my project and there was no information about this in the e-manual.

**Comment by ROBOTIS-Will** [comment]
Hi,
Please see below comment for each coordinate information.
```
room_1 :
name : toilet
object :
marker : ar_marker_0
position : [0.25, 0, 0.15] //Global coordinate of the object to grab with manipulator measured from the center of the marker.
target :
marker : ar_marker_4
position : [0.25, 0, 0.15] //Global coordinate where the object should be placed at.
x : [1.5, 0.6] //X coordinates of room 1 measured from the center of the arena.
y : [1.5, 0.2] //Y coordinates of room 1 measured from the center of the arena. With X and Y coordinates, when the robot moves to the room, calculate center coordinate of the room.
```
Thank you.

**Comment by ghost** [comment]
Hi @ROBOTIS-Will,

First of all thank you for all the explanations you've given, they really help me!

I don't quite understand the last two coordinates yet. You say that x : [1.5, 0.6] are the X coordinates of room 1 measured from the center of the arena. But X coordinates should only be one value right?

Or, am I reading those two blocks of coordinates wrong, and should it be interpreted more as:
`coordinates_1 : [1.5, 1.5] // X and Y coordinates of room 1 measured from the center of the arena
(this location is somewhat at the "entrance" of this room)`
`coordinates_2 : [0.6, 0.2] // X and Y coordinates of the center of room 1 (from which the AR tag should be visible)`

Is this the right way of thinking?

**Comment by ROBOTIS-Will** [comment]
@The3Designer 
Oh, sorry for unclear explanation. Please see below image for X and Y coordinates measured from the center where the TurtleBot3 is located at.
----Edited----
Sorry, X axis is vertical in below picture while Y axis is horizontal.
![image](https://user-images.githubusercontent.com/26239359/82418236-b4b9f580-9ab7-11ea-86ba-c45a5f9ce57b.png)

**Comment by ghost** [comment]
Ah, now the coordinates make sense, thanks a lot @ROBOTIS-Will !

And then, if I understand correctly, the TurtleBot3 will move to the center of that room (which it calculates itself). Once it reaches this center point, it will rotate to find the AR tag and once the camera sees that AR tag, the TurtleBot3 will move towards that AR tag. Is that correct?

**Comment by ROBOTIS-Will** [comment]
Sorry, X and Y axis are switched in the previous image. Please see updated image for correct coordinate expression. 
Yes, TurtleBot3 will use the center of room for the destination and then use the AR marker for precise approach.

**Comment by ghost** [comment]
Alright, everyting is fully clear for me. Thanks for your support and explanations Will :)
