### ISSUE TITLE
Question - Operation test messages for navigation

### ISSUE THREAD

**Issue by ghost** [ROBOTIS-GIT/turtlebot3_home_service_challenge#6]
Hi!

I have a question about these operation test messages for navigation that are listed in the e-manual:
`$ rostopic pub -1 /tb3_hsc/command std_msgs/String nav_ar_marker_0`
`$ rostopic pub -1 /tb3_hsc/command std_msgs/String nav_ar_marker_1`
`$ rostopic pub -1 /tb3_hsc/command std_msgs/String nav_ar_marker_2`

The questions I have is:
_What tasks will the Turtlebot perform when these messages are published? Are there specific tasks or a group of tasks from the scenario.yaml file that get triggered by these test messages? Or is/are the triggered task(s) not coming from this scenario.yaml file (if so then where are these commands listed)?_

Would, for example, publishing the message "nav_ar_marker_0" make the TurtleBot3 move to the location of that AR tag and also position itself in front of it (using the AR tag for accurate positioning)?

Hopefully someone can clarify this for me :)

**Comment by ROBOTIS-Will** [comment]
Hi,

Aforementioned commands are specific AR marker positioning test.
For example, when ar_marker_0 is detected, the robot will approach to the ar marker 0 with the distance of 0.35 meter using move_base in the navigation package.
If you need to execute specific scenarios separately, you can use below command.
```
$ rostopic pub -1 /tb3_hsc/command std_msgs/String restart_mission:SCENARIO_NAME
```
The SCENARIO_NAME can be found from the scenario.yaml file where each task is grouped with its scenario name.
```
# =================== room 1 ===================

find_object_1 :  // "find_object_1" is scenario name of this task.
  task : find_object
  args : [room_1, object]group
  timeout : 0 #sec, 0 : no time out
  next_scenario : nav_to_object_1
  scenario_on_failure : standby
  retry_times : 10  #times, 0 : no retry
```

**Comment by ghost** [comment]
Hi @ROBOTIS-Will,

Ah great, then I'll modify the scenario.yaml file slightly and use the restart_mission:SCENARIO_NAME to perform specific tasks. Thanks a lot for the explanation! I'll close this question then 👍
