### ISSUE TITLE
xacro: Traditional processing is deprecated

### ISSUE THREAD

**Issue by ghost** [ROBOTIS-GIT/turtlebot3_home_service_challenge#7]
This is an error I get immediatly after running the demo launch command:
![Screenshot from 2020-05-19 15-33-02](https://user-images.githubusercontent.com/59917065/82333155-d773dd80-99d5-11ea-8a3e-d7bf34c65c7d.png)

All the other steps of the tutorial gave me no issues, so I'm guessing this is an error in the code somewhere. I'm not sure if this has an effect or not, but I think it could be fixed either way.

**Comment by ROBOTIS-Will** [comment]
Hi,
If you are using Gazebo version higher than 7 with your ROS 1 Kinetic, above warning message could appear. Since it is a deprecation warning, you shouldn't have a problem with executing the launch file.
Thank you.

**Comment by ghost** [comment]
Hi @ROBOTIS-Will,
Thank you for the clarification! I'll close this issue then, since it's no problem.
