### ISSUE TITLE
[ERROR] No sensor plugin specified for octomap updater 0; ignoring

### ISSUE THREAD

**Issue by ghost** [ROBOTIS-GIT/turtlebot3_home_service_challenge#8]
Another error that I get when running the demo launch file:
![Screenshot from 2020-05-19 15-33-14](https://user-images.githubusercontent.com/59917065/82333382-3174a300-99d6-11ea-83e4-41ad6ad3dcdf.png)

Just as with the other errors, the "installation" and setup steps of this tutorial went fine. But now that I launch the actual project, I get a lot of errors. This is on a clean install of Ubuntu 16.04 running ROS 1 Kinetic.

**Comment by ROBOTIS-Will** [comment]
Hi,

The error is related to the Moveit plugin where OctoMap 3D mapping framework can be used.
Since Home service challenge does not require 3D sensors nor have to do with the octomap, you can simply ignore the error.
Thank you.

**Comment by ghost** [comment]
Hi @ROBOTIS-Will,
Thanks again for the clarification. This issue can be closed then :)
